from P_Simple import *
clear()


verb_ing= input ('Enter a verb ending in -ing: ')
adj = input ('Please enter a adjective: ')
noun = input ('Enter a noun: ')
plural_noun = input ('Enter a plural noun: ')
alive = ('Enter somthing alive (plural): ')
verb_ing2= input ('Enter a verb ending in -ing: ')
noun2 = input ('Enter a noun: ')
event = input('Enter an event (e.g party): ')
verb = input ('Enter a verb: ')
adj2 = input ('Please enter a adjective: ')
food = input ('Enter a type of food: ')
alive2 = input ('Enter somthing alive: ')
clothes = input ('Please enter a clothing item: ')
noun3 = input ('Enter a noun: ')
body_part = input ('Enter a random body part (PG please): ')
word = input ('Enter a random silly word: ')
plural_noun2 = input ('Enter a plural noun: ')
noun4 = input ('Enter a noun: ')

print ('\033[1mFrankenstein\'s diary\033[0m.')
print ('Dear Diary.')
print ('Today me have fun and go trick-or-',verb_ing,' for the first time.' )
print ('Good news is, face already look ' ,adj,', so me not have to wear Halloween ', noun,'.')
print ('Me see kids dressed as ',plural_noun, ' and ',alive,'.' )
print ('NO one afriad of me because they think me ',verb_ing2,' fake ',noun2,'.' )
print ('Next, me go with kids to Halloween ',event,'.')
print ('There, everyone ',verb,' to ',adj2, ' music and play Halloween games , like bobbing for ',food,'.')
print ('Me have lots of fun dancing with',alive2, '. Then, me win best',clothes,'contest')
print('When villigers try to take off me ',noun3, ', they realze it really is me ',body_part,'.')
print ('They scream \"',word,'\" and chase me away with pitchforks and ', plural_noun2 ,'.' )
print ('Me love Halloween and next year me want to go trick of treating dressed as a friendly ',noun4,'.')