import time
import os

def Ethan_madlib():
    print ('Turkey Picking\n')
    clock1 = input("Please insert a time(numberwise): ")
    adjective1 = input("Please insert an adjective: ")
    verb1 = input("Please insert a verb ending in \'ing\': ")
    color1 = input("Please insert a color: ")
    color2 = input("Please insert a different color: ")
    celebrity1 = input("Please insert a celebrity: ")
    person1 = input("Please insert a person: ")
    adjective2 = input("Please insert an adjective: ")
    animal1 = input("Please insert an animal: ")
    adverb1 = input("Please insert an adverb: ")
    shape1 = input("Please insert a shape: ")
    noun1 = input("Please insert a noun: ")
    adverb2 = input("Please insert an adverb: ")
    adjective3 = input("Please insert an adjective: ")
    anipart1 = input("Please insert an animal part: ")
    color3 = input("Please insert a color: ")
    number1 = input("Please insert a number: ")
    clock2 = input("Please insert a time(numberwise): ")
    feelly1 = input("Please insert a feeling ending in \'ly\': ")
    vehicle1 = input("Please insert a vehicle: ")
    print("You arrive at ",clock1," to the world\'s best turkey farm to get a",adjective1,"turkey.")
    print("You see hundreds of turkeys",verb1,"about. There were bright",color1,"turkeys")
    print("and dark",color2,"turkeys. Your wondering how you would be able to pick when",celebrity1,"and",person1,"walk up")
    print("to you in",adjective2,"clothes.",person1,"has a(n)",animal1,"in their arms. You",adverb1,"give them a smile.")
    print("They open the",shape1,"gate to the",noun1,"so you can pick a turkey, which are running around",adverb2,".")
    print("It takes you some time to look through your options of",adjective3,"turkeys, but you eventually find the perfect one.")
    print("It has (a)",anipart1,"that is/are",color3,". You go to pay but the turkey cost",number1,"dollar(s)")
    print("and you don\'t have that much money. It's",clock2,"when you",feelly1,"leave the turkey farm in")
    print("your",vehicle1,". Looks like it is the yucky store bought turkey again for you this year. Sorry.")
    time.sleep(60)
