import os

def madlib ():
    print ('Pie baking\n')
    person = input ('Enter a person in the room: ')
    place= input('Etner a random place: ')
    adj= input ('Enter a random adjective: ')
    food1=input ('Enter a type of food: ')
    food2=input ('Enter another type of food: ')
    food3=input ('Enter a thrid type of food: ')
    place2= input('Enter a random place: ')
    person2= input ('Enter a different person in the room: ')
    excl=input ('Enter a random exclamations (i.e zoinks,wow,dang,drat..ext: ')
    time_of_day = input ('Enter a random time of day (i.e tonight, tomorrow, in the morning: ')
    verb = input ('Enter a random verb: ')
    verb2 = input ('Enter another random verb: ')
    number = input ('Enter a random number: ')
    room = input ('Enter a random name of a room(i.e bedroom, kitchen): ')
    verb3 = input ('Enter a random verb: ')
    adj2 = input ('Enter a random adjective: ')
    food4 = input ('Enter a random food: ')
    food5 = input ('Enter another random food: ')
    verb4= input ('Enter a verb: ')
    room2 = input ('Enter a random name of a room(i.e bedroom, kitchen): ')

    print ('\nIt was the day before Thanksgiving and' , person , 'went to the ',place,'to get all of the ingredients to make their', adj, 'pie.')
    print (person,' picked up', food1, food2, 'and', food3, 'at the', place, ' and headed to the',place2,'.')
    print ('When' ,person, 'got to',place2, ',they saw',person2,'and said"', excl, '!',time_of_day , 'we are going to', verb, 'the pie. Before we do that, I am going to', verb2, 'a nap"\n')
    print (number, 'Hours later.\n')
    print (person, 'looked all around the', place, 'for', person2,'.')
    print ('"Where did they go? Are they hiding in the',room,'?"')
    print ('All of a sudden', person2, verb3,'up and says, "Is it time to make the pie?" They started to make the pie with the',food1,',',food2,'and',food3,'.')
    print ('They also added the' ,adj2 , 'ingredients of', food4, 'and', food5, '.')
    print ('After they made the pie, they',verb4, 'they pie in the',room2,'.')
