personinroom1 = input ( 'Please enter a name a person in the room: ' )
number = input ( 'Please enter a random number: ')
adjective = input ( 'Please enter a random adjective: ')
color = input ( 'Please enter a random color: ')
noun = input ( 'Please enter a random noun: ')
food = input ( 'Please enter a random plural food: ')
noun2= input ( 'Please enter a random noun: ')
verb = input ( 'Please enter a random verb ending in ing: ')
clothing = input ( 'Please enter a random clothing item: ')
adjective2 = input ( 'Please enter a random adjective: ')
celeberity = input ( 'Please enter a random celebrity: ')
number2 = input ( 'Please enter a random number: ')
peronsinroom2  = input ( 'Please enter a random peron in the room: ')
noun3 = input ( 'Please enter a random noun: ')
peronsinroom3  = input ( 'Please enter a random peron in the room: ')
occupation = input ( 'Please enter a random job: ')
print ("My name is",personinroom1," and I am",number, "years old.")
print ("If I were president, I\'d do a whole bunch of" ,adjective,"things.")
print ("I would drive the biggest", color,"car in the country.")
print ("And taht car would go faster than any other",noun,"in the world!")
print ("Everyone would eat pepperoni",food, "for dinner.")
print ("I would live in the Statue of",noun2,"and build a",verb,"pool at her feet")
print ("I would wear a/an",clothing,"on my head")
print ("and everyone would say I look",adjective2, "like",celeberity)
print ("School woudl be opne only",number2,"days a year")
print ("I would give my frines the best jobs.")
print ("I would nominate",peronsinroom2," to be secretary of (the)",noun3)
print ("and",peronsinroom3,"could be vice",occupation,".")
