import time
import os 
from Simple import *
#Creator: Ethan 
def decorate ():
    color1 = input("Please insert a color: ")
    country1 = input("Please insert a country: ")
    adjective1 = input("Please insert an adjective: ")
    adverb1 = input("Please insert an adverb: ")
    adjective2 = input("Please insert an adjective: ")
    build1 = input("Please insert a building: ")
    shape1 = input("Please insert a shape: ")
    number1 = input("Please insert a number: ")
    shape2 = input("Please insert a shape: ")
    color2 = input("Please insert a color: ")
    adverb2 = input("Please insert an adverb: ")
    emotion1 = input("Please insert an emotion: ")
    candy1 = input("Please insert a christmas candy: ")
    materiaL1 = input("Please insert a material: ")
    movie1 = input("Please insert a christmas movie: ")
    fast_food1 = input("Please insert a fast food place: ")
    time1 = input("Please insert a number between 1 and 12: ")
    percent1 = input("Please insert a percent between 1 and 50: ")
    verb1 = input("Please insert a verb: ")
    exclaimation1 = input("Please insert an exclaimation: ")
    print("You see",color1,"snow falling outside. Winter has finally here come to",country1,".")
    print("You put on your",adjective1,'coat and',adverb1,'slip on your boots to go pick out a christmas tree.')
    print('You choose a',adjective2,'tree and take it inside your',build1,'to decorate. Lights are wrapped around')
    print('the tree that are shaped like',shape1,'and a train with',number1,'train cars is driving around the trunk of the tree.')
    print('You begin to',shape2,'wrapped',color2,'tinsel around your tree. You put red, green and gold ornaments on.')
    print('The whole job',adverb2,'by in your',emotion1,'. You start to put',candy1,'in a',materiaL1,'container.')
    print('You feel like watching',movie1,'tonight in the spirit of christmas, as you put the star on top of the tree.')
    print('You start to prepare your oven for dinner when you decide to order',fast_food1,'instead.')
    print('It arrives at',time1,' o\'clock and you give the delivery person a',percent1,'% tip as they leave.')
    print('You sit down and relax as you',verb1,'over what you have accompliced today. Yet you still have much left to do.')
    print('\'',exclaimation1,'\' you say out loud, \'There are still 24 days until christmas. I still have lots of time left.\'')
    
